version: "3.8"

services:
  db:
    container_name: mysql_playground_db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.local
    ports:
      - "3640:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  
  pma:
    container_name: mysql_playground_pma
    image: phpmyadmin:latest
    restart: always
    environment:
      UPLOAD_LIMIT: 950M
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8895:80"
    links:
      - db
volumes:
  mysql_data:
